# Default values for cdp-service DEV.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: preprod
image:
  repository: dcxregistry.azurecr.io/fletum/cdp-service
  tag: latest

fletum_api_base_url: preprodValue
validation_microservice_base_url: preprodValue
identity_microservice_base_url: preprodValue
create_entity_base_url: preprodValue
otp_service_base_url: preprodValue
urls: preprodValue
###### SECRETS ######
connection_string_default_conn: preprodValue
telegram_chatid: preprodValue
telegram_key: preprodValue