# Default values for cdp-service DEV.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: prod
image:
  repository: dcxregistry.azurecr.io/fletum/cdp-service
  tag: latest

fletum_api_base_url: prodValue
validation_microservice_base_url: prodValue
identity_microservice_base_url: prodValue
create_entity_base_url: prodValue
otp_service_base_url: prodValue
urls: prodValue
###### SECRETS ######
connection_string_default_conn: prodValue
telegram_chatid: prodValue
telegram_key: prodValue