apiVersion: apps/v1
kind: Deployment
metadata:
  name: otp
  labels:
    app: otp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otp
  template:
    metadata:
      labels:
        app: otp
    spec:
      imagePullSecrets:
      - name: dcxregistry
      containers:
      - name: otp
        image: dcxregistry.azurecr.io/fletum/otp-service
        ports:
        - containerPort: 8089
        env:
            - name: URLs
              value: http://otp-service:8089
