apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
  labels:
    app: identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      imagePullSecrets:
      - name: dcxregistry
      containers:
      - name: identity
        image: dcxregistry.azurecr.io/fletum/identity-service
        ports:
        - containerPort: 8989
        env:
            - name: URLs
              value: http://identity-service:8989
            - name: ConnectionStrings__DefaultConnection
              value: Data Source=10.8.4.69;Initial Catalog=CCICDPTest;Persist Security Info=True;User ID= cdpdevuser;Password=dd!2A23323!!;MultipleActiveResultSets=True;