# Default values for bpm-service DEV.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: prod
image:
  repository: dcxregistry.azurecr.io/fletum/bpm-service
  tag: latest

urls: prodValue