#trigger:

#- master
pool:
  vmImage: 'ubuntu-latest'
resources:
  repositories:
  - repository: self
    type: git
    name: CCI/rating-web.git
    trigger:
    - master
  - repository: templates
    type: github
    name: altugyildirim/azure-pipelines-templates
    endpoint: github

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build_web
    displayName: Build Web
    steps:
      - template: ./pipelines/build-template.yml@templates
        parameters:
          workingDirectory: '$(Build.Repository.LocalPath)/src'
          toolset: none
- stage: Test
  displayName: Test stage
  jobs:  
  - job: Test_web
    displayName: Test web
    steps:
      - template: ./pipelines/sonarcloud-template.yml@templates
        parameters:
          workingDirectory: '$(Build.Repository.LocalPath)/src'
- stage: Build_dockerimage
  displayName: Build and push image to ACR stage
  jobs:  
  - job: Build_web_dockerimage
    displayName: Build and push web image
    steps:
      - template: ./pipelines/docker-template.yml@templates
        parameters:
          workingDirectory: '$(Build.Repository.LocalPath)/'
          quay_password: '$(quay_password)'
- stage: ArgoCD_Delivery 
  displayName: ArgoCD Delivery 
  jobs:  
  - job: ArgoCD_Delivery 
    displayName: ArgoCD Delivery steps
    steps:
      - template: ./pipelines/argocd-delivery-template.yml@templates
        parameters:
          workingDirectory: '$(Build.Repository.LocalPath)/.'
