apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation
  labels:
    app: validation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validation
  template:
    metadata:
      labels:
        app: validation
    spec:
      imagePullSecrets:
      - name: dcxregistry
      containers:
      - name: validation
        image: dcxregistry.azurecr.io/fletum/validation-service
        ports:
        - containerPort: 8010
