apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpm
  labels:
    app: bpm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpm
  template:
    metadata:
      labels:
        app: bpm
    spec:
      imagePullSecrets:
      - name: dcxregistry
      containers:
      - name: bpm
        image: dcxregistry.azurecr.io/fletum/bpm-service
        ports:
        - containerPort: 8087
        env:
            - name: URLs
              value: http://bpm-service:8087
