apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.registrySecret.name }}
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ .Values.registrySecret.config | toJson | b64enc | quote }}
type: kubernetes.io/dockerconfigjson