apiVersion: v1
kind: Secret
metadata:
  name: sec-{{ .Values.application }}-{{ .Values.environment }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  connection-string-default-conn: "{{ .Values.connection_string_default_conn }}"
  telegram-chatid: "{{ .Values.telegram_chatid }}"
  telegram-key: "{{ .Values.telegram_key }}"

#data:
#  key1: value1 #base64encoded
#  key2: value2 #base64encoded